{{- if .Values.apps.minio-app | default false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-app
  namespace: argocd  # Change if ArgoCD is installed in a different namespace
spec:
  project: default
  source:
    repoURL: https://operator.min.io
    chart: operator
    targetRevision: "7.0.0"  # Check for the latest version on Artifact Hub
    helm: # overwrite helm values here
      releaseName: minio-operator

  destination:
    server: https://kubernetes.default.svc  # Deploy to the in-cluster Kubernetes API
    namespace: "{{ .Values.namespace }}"  # MinIO will be installed in this namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
