apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/trongtruong2509/argocd-demo.git
    targetRevision: approach_2
    path: "helm-charts/nginx-demo"
    helm:
      values: | 
        replicaCount: 1
        image:
          repository: nginx
          tag: "latest"
          pullPolicy: Always
        dependency: []

        deployment:
          environment: "development"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: "nginx-demo"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
