cluster_name: minikube
# namespace: dev

apps:
  minio-app: true
  my-nginx-app: true
  

my_nginx_app:
  replicaCount: 1
  image:
    repository: nginx
    tag: "latest"
    pullPolicy: Always
  dependency: []

  deployment:
    environment: "development"
